/*
 * File: AccountPanel.ui.js
 * Date: Fri Jul 23 2010 16:17:26 GMT+0200 (Rom, sommertid)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.7.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

AccountPanelUi = Ext.extend(Ext.Panel, {
    title: 'Account',
    height: 473,
    initComponent: function() {
        this.items = [
            {
                xtype: 'label',
                text: 'Crawl Limit',
                width: 200
            },
            {
                xtype: 'numberfield',
                id: 'acountCrawlLimit'
            },
            {
                xtype: 'spacer'
            },
            {
                xtype: 'label',
                text: 'Level Limit'
            },
            {
                xtype: 'numberfield',
                id: 'levelLimit'
            },
            {
                xtype: 'grid',
                title: 'domains',
                height: 285,
                width: 386,
                columns: [
                    {
                        xtype: 'gridcolumn',
                        dataIndex: 'string',
                        header: 'domain',
                        sortable: true,
                        width: 100
                    }
                ]
            }
        ];
        AccountPanelUi.superclass.initComponent.call(this);
    }
});
