/*
 * File: AdministrationPanel.ui.js
 * Date: Thu Jul 29 2010 22:17:54 GMT+0200 (Rom, sommertid)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.7.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

AdministrationPanelUi = Ext.extend(Ext.Panel, {
    title: 'Search Engine Administration',
    width: 800,
    height: 400,
    id: 'AdmnistrationPanel',
    initComponent: function() {
        this.items = [
            {
                height: 400,
                width: 800,
                xtype: 'configurationtabpanel'
            }
        ];
        this.tbar = {
            xtype: 'configurationtoolbar'
        };
        AdministrationPanelUi.superclass.initComponent.call(this);
    }
});
