/*
 * File: AdministrationPanel.ui.js
 * Date: Fri Jul 23 2010 16:17:26 GMT+0200 (Rom, sommertid)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.7.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

AdministrationPanelUi = Ext.extend(Ext.Panel, {
    title: 'Search Engine Administration',
    width: 847,
    height: 464,
    initComponent: function() {
        this.items = [
            {
                height: 310,
                xtype: 'collecitonconfigurationtabpanel'
            }
        ];
        this.tbar = {
            xtype: 'administratiotoolbar'
        };
        AdministrationPanelUi.superclass.initComponent.call(this);
    }
});
