/*
 * File: CollectionSettingsPanel.ui.js
 * Date: Thu Jul 29 2010 17:11:27 GMT+0200 (Rom, sommertid)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.7.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

CollectionSettingsPanelUi = Ext.extend(Ext.Panel, {
    title: 'Collection settings',
    height: 400,
    width: 689,
    initComponent: function() {
        this.items = [
            {
                xtype: 'label',
                text: 'Crawl Limit',
                width: 200
            },
            {
                xtype: 'numberfield',
                id: 'crawlLimit'
            },
            {
                xtype: 'spacer'
            },
            {
                xtype: 'label',
                text: 'Level Limit'
            },
            {
                xtype: 'numberfield',
                id: 'levelLimit'
            },
            {
                xtype: 'mygrid'
            }
        ];
        CollectionSettingsPanelUi.superclass.initComponent.call(this);
    }
});
