/*
 * File: CollectionStore.js
 * Date: Tue Aug 03 2010 21:52:38 GMT+0200 (Rom, sommertid)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.7.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

CollectionStore = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        CollectionStore.superclass.constructor.call(this, Ext.apply({
            storeId: 'CollectionStore',
            url: 'app.php?controller=Collection',
            restful: true,
            paramNames: {
                start: "start",
                limit: "limit",
                sort: "sort",
                dir: "dir",
                collectionId: "collectionId"
            },
            fields: [
                {
                    name: 'name'
                },
                {
                    name: 'startURL'
                },
                {
                    name: 'pageLimit'
                },
                {
                    name: 'levelLimit'
                },
                {
                    name: 'id'
                }
            ]
        }, cfg));
    }
});
new CollectionStore();