/*
 * File: ConfigurationToolBar.js
 * Date: Thu Jul 29 2010 17:23:08 GMT+0200 (Rom, sommertid)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.7.
 * http://www.extjs.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

ConfigurationToolBar = Ext.extend(ConfigurationToolBarUi, {
    initComponent: function() {
        ConfigurationToolBar.superclass.initComponent.call(this);
    }
});
Ext.reg('configurationtoolbar', ConfigurationToolBar);