/*
 * File: ConfigurationToolBar.ui.js
 * Date: Thu Jul 29 2010 20:40:45 GMT+0200 (Rom, sommertid)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.7.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

ConfigurationToolBarUi = Ext.extend(Ext.Toolbar, {
    itemId: 'AdministrationToolBar',
    id: 'AdministrationToolBar',
    initComponent: function() {
        this.items = [
            {
                xtype: 'button',
                text: 'Save Changes'
            }
        ];
        ConfigurationToolBarUi.superclass.initComponent.call(this);
    }
});
