/*
 * File: ConfigurationToolBar.ui.js
 * Date: Sun Sep 12 2010 08:33:48 GMT+0200 (CEST)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

ConfigurationToolBarUi = Ext.extend(Ext.Toolbar, {
    itemId: 'AdministrationToolBar',
    id: 'AdministrationToolBar',
    initComponent: function() {
        this.items = [
            {
                xtype: 'button',
                text: 'Save Changes'
            },
            {
                xtype: 'button',
                text: 'Start / Restart'
            }
        ];
        ConfigurationToolBarUi.superclass.initComponent.call(this);
    }
});
