/*
 * File: CrawlerPanel.js
 * Date: Fri Jul 23 2010 15:52:08 GMT+0200 (Rom, sommertid)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.7.
 * http://www.extjs.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

CrawlerPanel = Ext.extend(CrawlerPanelUi, {
    initComponent: function() {
        CrawlerPanel.superclass.initComponent.call(this);
    }
});
Ext.reg('crawlerpanel', CrawlerPanel);