/*
 * File: CrawlerFilterToolBar.ui.js
 * Date: Thu Jul 29 2010 22:17:54 GMT+0200 (Rom, sommertid)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.7.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

CrawlerFilterToolBarUi = Ext.extend(Ext.Toolbar, {
    initComponent: function() {
        this.items = [
            {
                xtype: 'button',
                text: 'Add',
                id: 'AddButton'
            },
            {
                xtype: 'button',
                text: 'Save',
                id: 'SaveButton'
            },
            {
                xtype: 'button',
                text: 'Delete',
                id: 'DeleteButton'
            }
        ];
        CrawlerFilterToolBarUi.superclass.initComponent.call(this);
    }
});
