/*
 * File: CrawlerPanel.ui.js
 * Date: Fri Jul 23 2010 16:17:26 GMT+0200 (Rom, sommertid)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.7.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

CrawlerPanelUi = Ext.extend(Ext.Panel, {
    title: 'Crawler',
    height: 539,
    initComponent: function() {
        this.items = [
            {
                xtype: 'crawlerfiltergridpanel'
            }
        ];
        CrawlerPanelUi.superclass.initComponent.call(this);
    }
});
