/*
 * File: CrawlerPanel.ui.js
 * Date: Thu Jul 29 2010 17:11:27 GMT+0200 (Rom, sommertid)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.7.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

CrawlerPanelUi = Ext.extend(Ext.Panel, {
    title: 'Crawler',
    height: 400,
    width: 800,
    initComponent: function() {
        CrawlerPanelUi.superclass.initComponent.call(this);
    }
});
