/*
 * File: CrawlerFilterGridPanel.ui.js
 * Date: Fri Jul 23 2010 16:17:26 GMT+0200 (Rom, sommertid)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.7.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

CrawlerFilterGridPanelUi = Ext.extend(Ext.grid.GridPanel, {
    title: 'Crawler Filter',
    initComponent: function() {
        this.columns = [
            {
                xtype: 'gridcolumn',
                dataIndex: 'number',
                header: 'domain',
                sortable: true,
                width: 100,
                align: 'right'
            },
            {
                xtype: 'gridcolumn',
                dataIndex: 'string',
                header: 'page prefix',
                sortable: true,
                width: 100
            },
            {
                xtype: 'booleancolumn',
                header: 'exclude',
                sortable: true,
                width: 100
            }
        ];
        this.tbar = {
            xtype: 'crawlerfiltertoolbar'
        };
        CrawlerFilterGridPanelUi.superclass.initComponent.call(this);
    }
});
