/*
 * File: DomainStore.js
 * Date: Sun Sep 12 2010 08:33:48 GMT+0200 (CEST)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

DomainStore = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        DomainStore.superclass.constructor.call(this, Ext.apply({
            storeId: 'DomainStore',
            autoSave: false,
            fields: [
                {
                    name: 'domain'
                }
            ]
        }, cfg));
    }
});
new DomainStore();