/*
 * File: DomainStore.js
 * Date: Tue Aug 03 2010 21:52:38 GMT+0200 (Rom, sommertid)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.7.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

DomainStore = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        DomainStore.superclass.constructor.call(this, Ext.apply({
            storeId: 'DomainStore',
            url: 'app.php?controller=domain',
            autoLoad: true,
            restful: true,
            api: '',
            fields: [
                {
                    name: 'domainid'
                },
                {
                    name: 'regex'
                }
            ]
        }, cfg));
    }
});
new DomainStore();