/*
 * File: IndexerStore.js
 * Date: Fri Jul 23 2010 18:55:31 GMT+0200 (Rom, sommertid)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.7.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

IndexerStore = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        IndexerStore.superclass.constructor.call(this, Ext.apply({
            storeId: 'IndexerStore'
        }, cfg));
    }
});
new IndexerStore();