/*
 * File: IndexerPanel.ui.js
 * Date: Fri Jul 23 2010 18:55:31 GMT+0200 (Rom, sommertid)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.7.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

IndexerPanelUi = Ext.extend(Ext.Panel, {
    title: 'Indexer',
    initComponent: function() {
        IndexerPanelUi.superclass.initComponent.call(this);
    }
});
