/*
 * File: IndexerFilterGridPanel.js
 * Date: Fri Jul 23 2010 16:17:26 GMT+0200 (Rom, sommertid)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.7.
 * http://www.extjs.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

IndexerFilterGridPanel = Ext.extend(IndexerFilterGridPanelUi, {
    initComponent: function() {
        IndexerFilterGridPanel.superclass.initComponent.call(this);
    }
});
Ext.reg('indexerfiltergridpanel', IndexerFilterGridPanel);