/*
 * File: xds_index.js
 * Date: Thu Jul 29 2010 22:12:00 GMT+0200 (Rom, sommertid)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.7.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.onReady(function() {
    var cmp1 = new AdministrationPanel({
        renderTo: Ext.getBody()
    });
    cmp1.show();
});
