/*
 * File: YASE.ui.js
 * Date: Sat Sep 18 2010 17:28:46 GMT+0200 (CEST)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

YASEUi = Ext.extend(Ext.Viewport, {
    layout: 'border',
    initComponent: function() {
        this.items = [
            {
                xtype: 'panel',
                title: 'Actions',
                region: 'center'
            }
        ];
        YASEUi.superclass.initComponent.call(this);
    }
});
