/*
 * File: YASE.ui.js
 * Date: Sat Sep 18 2010 20:34:24 GMT+0200 (CEST)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

YASEUi = Ext.extend(Ext.Viewport, {
  layout: 'border',
  initComponent: function() {
    this.items = [
      {
        xtype: 'tabpanel',
        title: 'Search Engine Administration',
        region: 'center',
        activeTab: 0
      }
    ];
    YASEUi.superclass.initComponent.call(this);
  }
});
